---
- name: Fetch PGDG repo key file
  get_url:
    url: "{{ pgdg_apt_repokey_url }}"
    dest: /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg.asc
    owner: root
    group: root
    mode: '0644'

- name: Import PGDG repo key
  apt_key:
    file: /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg.asc
    state: present

- name: Install PGDG repo file
  apt_repository:
    repo: "deb {{ pgdg_apt_repo_url }} {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: pgdg.list

- name: Refresh apt metadata
  apt:
    update_cache: yes
