---

- name: redhat install
  include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: debian install
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: suse install
  include_tasks: suse.yml
  when: ansible_os_family == 'Suse'
