---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: centos:centos7
    pre_build_image: true
  - name: alma8
    image: almalinux:8
    pre_build_image: true
  - name: alma9
    image: almalinux:9
    pre_build_image: true
  - name: rhel_ubi8
    image: rhel_ubi8
    dockerfile: dockerfile.ubi8
  - name: fedora35
    image: fedora:35
    pre_build_image: true
  - name: fedora36
    image: fedora:36
    pre_build_image: true
  - name: ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible
    pre_build_image: true
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
  - name: ubuntu2204
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
  - name: debian10
    image: python:buster
    pre_build_image: true
  - name: debian11
    image: python:bullseye
    pre_build_image: true
  - name: opensuse_leap
    image: opensuse_leap
    dockerfile: dockerfile.leap
  - name: sle_bci
    image: registry.suse.com/bci/python
    pre_build_image: yes
provisioner:
  name: ansible
verifier:
  name: ansible
lint: ansible-lint
